
/*Siga los siguientes pasos*/

/*Base de Datos*/
CREATE DATABASE FACTURACION;


USE facturacion;

/*tabla cliente*/

CREATE TABLE REPRESENTANTE (
IDENTIFICACION_REPRESENTANTE INT(10) NOT NULL AUTO_INCREMENT,
USUARIO VARCHAR(35),
PASSWORD VARCHAR(50) NOT NULL,
PRIMARY KEY(IDENTIFICACION_REPRESENTANTE)
);

CREATE TABLE EMPRESA (
NIT_EMPRESA INT(10) NOT NULL AUTO_INCREMENT,
REGIMEN_CONTRIBUTIVO  VARCHAR(35) NOT NULL,
NOMBRE_COMERCIAL  VARCHAR(35) NOT NULL,
PAIS  VARCHAR(35) NOT NULL,
DEPARTAMENTO  VARCHAR(35) NOT NULL,
CIUDAD VARCHAR(35) NOT NULL,
LOGO LONGBLOB NOT NULL,
RESOLUCION_DIAN VARCHAR(35) NOT NULL,
DIRECCION VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(35) NOT NULL,
NOMBRE_REGISTRO VARCHAR(35) NOT NULL,
IDENTIFICACION_REPRESENTANTE VARCHAR(35) NOT NULL,
NOMBRE_REPRESENTANTE VARCHAR(35) NOT NULL,
APELLIDO_REPRESENTANTE VARCHAR(35) NOT NULL,
CORREO_REPRESENTANTE VARCHAR(35) NOT NULL,
PRIMARY KEY(NIT_EMPRESA)
);


/*CREATE TABLE factura (

id_factura INT(10) NOT NULL AUTO_INCREMENT,
facha DATE NOT NULL,
nit INT(5) NOT NULL,
valor_total Int(50) NOT NULL,
PRIMARY KEY(id_factura)
);*/

