
/*Siga los siguientes pasos*/

/*Base de Datos*/
CREATE DATABASE facturacion;

USE facturacion;

/*tabla cliente*/

CREATE TABLE representante (

cedula INT(12) NOT NULL AUTO_INCREMENT,
usuario VARCHAR(35) NOT NULL,
contrasena VARCHAR(50) NOT NULL,
PRIMARY KEY(cedula)
);

CREATE TABLE empresa (

NIT_EMPRESA INT(10) NOT NULL AUTO_INCREMENT,
REGIMEN_CONTRIBUTIVO  VARCHAR(35) NOT NULL,
NOMBRE_COMERCIAL  VARCHAR(35) NOT NULL,
PAIS  VARCHAR(35) NOT NULL,
DEPARTAMENTO  VARCHAR(35) NOT NULL,
CIUDAD VARCHAR(35) NOT NULL,
LOGO VARCHAR(35) NOT NULL,
RESOLUCION_DIAN VARCHAR(35) NOT NULL,
DIRECCION VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(35) NOT NULL,
NOMBRE_REGISTRO VARCHAR(35) NOT NULL,
IDENTIFICACION_REPRESENTANTE VARCHAR(35) NOT NULL,
NOMBRE_REPRESENTANTE VARCHAR(35) NOT NULL,
APELLIDO_REPRESENTANTE VARCHAR(35) NOT NULL,
PRIMARY KEY(NIT_EMPRESA)
);


CREATE TABLE factura (

id_factura INT(10) NOT NULL AUTO_INCREMENT,
facha DATE NOT NULL,
nit INT(5) NOT NULL,
valor_total Int(50) NOT NULL,
PRIMARY KEY(id_factura)
);

